from enum import StrEnum, unique


@unique
class InterviewType(StrEnum):
    HR_SCREEN = "HR_SCREEN"
    PHONE_SCREEN = "PHONE_SCREEN"
    TECHNICAL = "TECHNICAL"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    TAKE_HOME = "TAKE_HOME"
    PAIR_PROGRAMMING = "PAIR_PROGRAMMING"
    MANAGER = "MANAGER"
    FINAL = "FINAL"
    OFFER_DISCUSSION = "OFFER_DISCUSSION"
    OTHER = "OTHER"
