from enum import StrEnum, unique


@unique
class JobEventType(StrEnum):
    NOTE = "NOTE"
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    EMAIL_RECEIVED = "EMAIL_RECEIVED"
    SALARY_UPDATE = "SALARY_UPDATE"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    REJECTION_RECEIVED = "REJECTION_RECEIVED"
    FOLLOW_UP = "FOLLOW_UP"
    OTHER = "OTHER"
